// Backend service - communicates with Go backend via Wails bindings.
// These functions are type-safe wrappers around the Go App service methods.

// The actual binding imports will be generated by:
//   wails3 generate bindings
// For now, we define the interface manually.

export interface AppService {
  GetVersion(): Promise<string>
  GetDependencies(): Promise<import("../types").DepResult>
  RefreshDependencies(): Promise<import("../types").DepResult>
  GetConfig(): Promise<import("../types").Config>
  SaveConfig(cfg: import("../types").Config): Promise<void>
}
